# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)
np.show_config()

1.13.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_opt_info:
    extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_opt_info:
    extra_compile_args = ['-msse3']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

#### 4.  How to find the memory size of any array (★☆☆)

In [ ]:
Z = np.ones((10,10))

print("%d" )

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [174]:
%run `python -c "import numpy; numpy.info(numpy.add) "`

ERROR:root:File `'`python3.py'` not found.


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [172]:
V = np.zeros(10)
V[4] = 1
print(V)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [170]:
V = np.random.random(10)
print(V)
print(V[::-1])

[  8.59077192e-01   6.09499468e-01   9.37298451e-01   5.48153612e-01
   3.67990891e-04   8.30257704e-01   2.59899077e-01   3.73095356e-01
   4.75273933e-01   5.17762989e-01]
[  5.17762989e-01   4.75273933e-01   3.73095356e-01   2.59899077e-01
   8.30257704e-01   3.67990891e-04   5.48153612e-01   9.37298451e-01
   6.09499468e-01   8.59077192e-01]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [166]:
print(np.random.uniform(0, 8, 9).reshape(3,3))

[[ 4.10195809  5.0199431   4.00777795]
 [ 0.75780301  7.37631518  0.02699029]
 [ 7.31975418  0.251051    6.17316115]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [165]:
A = [1,2,0,0,4,0]
print(np.nonzero(A))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [164]:
print(np.eye(3)) #np.eye()

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [160]:
M = np.random.random((3,3,3))
print(M)

[[[ 0.43896299  0.80526253  0.63690467]
  [ 0.70488428  0.52627887  0.15725016]
  [ 0.26845415  0.18838932  0.48100172]]

 [[ 0.56027193  0.47308984  0.24147254]
  [ 0.83536499  0.21595977  0.2644754 ]
  [ 0.28202049  0.3695089   0.56907224]]

 [[ 0.73877286  0.68304671  0.78073319]
  [ 0.78941604  0.70114605  0.00294553]
  [ 0.02188158  0.12412761  0.99344579]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [159]:
M = np.random.random((10, 10))
print(M.min(), M.max())


0.00561091801016 0.988471948677


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [156]:
print(np.random.random(size = 30).mean())

0.582477068868


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [154]:
A = np.zeros((2,2))

B = np.pad(A, pad_width = 1, mode ='constant', constant_values = 1)
print(B)

[[ 1.  1.  1.  1.]
 [ 1.  0.  0.  1.]
 [ 1.  0.  0.  1.]
 [ 1.  1.  1.  1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [152]:
A = np.ones((4,4))
print(A)

B = np.pad(A, pad_width =1, mode = 'constant', constant_values = 0)
print(B)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [147]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [141]:
print(np.diag(1 + np.arange(4), k = -1)) #interesting!!!

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
# checkerboard pattern?

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [136]:
print(np.unravel_index(55, (6,7,8)))

(0, 6, 7)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
# tile function?

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [125]:
M = np.random.uniform(0, 1, 25).reshape(5,5)
print(M)

print((M - np.mean(M) / np.std(M)))

# print(np.mean(M))

[[ 0.10858427  0.27995055  0.56714686  0.63636379  0.65916088]
 [ 0.70793884  0.79460962  0.77055278  0.13201372  0.75455585]
 [ 0.89267078  0.84821528  0.69055986  0.40340164  0.68135501]
 [ 0.17844833  0.90712154  0.01014318  0.73057865  0.88877149]
 [ 0.34494433  0.45659776  0.50501793  0.47195606  0.73798493]]
[[-2.06694747 -1.89558119 -1.60838487 -1.53916794 -1.51637086]
 [-1.4675929  -1.38092212 -1.40497896 -2.04351802 -1.42097588]
 [-1.28286096 -1.32731646 -1.48497188 -1.7721301  -1.49417673]
 [-1.99708341 -1.26841019 -2.16538856 -1.44495308 -1.28676025]
 [-1.83058741 -1.71893398 -1.6705138  -1.70357568 -1.43754681]]
0.566345756604


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [122]:
A = np.random.normal(size = 15).reshape(5,3)
print(A)

B = np.ones((3,2))*0.5
print(B)

print(np.dot(A, B))

print(A @ B) #np.dot and @ operator

[[-0.56000048 -0.60522399  0.39956019]
 [ 0.16011008  0.70844039  0.2787757 ]
 [ 0.98078261  1.12629083 -0.53894593]
 [-0.14759595  0.46268406  2.06547442]
 [-0.3149883   1.54333859 -0.84111909]]
[[ 0.5  0.5]
 [ 0.5  0.5]
 [ 0.5  0.5]]
[[-0.38283214 -0.38283214]
 [ 0.57366309  0.57366309]
 [ 0.78406376  0.78406376]
 [ 1.19028126  1.19028126]
 [ 0.1936156   0.1936156 ]]
[[-0.38283214 -0.38283214]
 [ 0.57366309  0.57366309]
 [ 0.78406376  0.78406376]
 [ 1.19028126  1.19028126]
 [ 0.1936156   0.1936156 ]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [115]:
A = np.arange(-10, 10)
print(A)

A[(A>=3) & (A<=8)] *= -1
print(A)

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9]
[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2  -3  -4  -5  -6  -7
  -8   9]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [107]:
print(sum(range(5),-1))

from numpy import *
print(sum(range(5),-1))# why?
print(sum(range(5)))

10
10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [103]:
Z = np.random.randint(0, 10, 4)
print(Z)

print(Z**Z)

print(2 << Z >> 2) # meaning?

# pirnt(Z <- Z)

print(1j*Z) #1j?

print(Z/1/1)

# print(Z<Z>Z)



[7 3 9 9]
[   823543        27 387420489 387420489]
[ 64   4 256 256]
[ 0.+7.j  0.+3.j  0.+9.j  0.+9.j]
[ 7.  3.  9.  9.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [94]:
print(np.array(0) / np.array(0))

print(np.array(0) // np.array(0))

print(np.array([np.nan]).astype(int).astype(float))

nan
0
[ -9.22337204e+18]


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


#### 29. How to round away from zero a float array ? (★☆☆)

In [91]:
A = np.random.uniform(-10, 10, 10)
print(A)

print(np.copysign(np.ceil(np.abs(A)), A)) # np.copysign()

[-0.47688071  9.17588535 -8.75397385 -8.31189524 -8.4352092   9.90966928
  6.53872662 -2.96141091 -0.93488067 -8.68392448]
[ -1.  10.  -9.  -9.  -9.  10.   7.  -3.  -1.  -9.]


#### 30. How to find common values between two arrays? (★☆☆)

In [88]:
A = np.random.randint(1, 10, 10)
B = np.random.randint(2, 11, 10)

print(A, B)


print(np.intersect1d(A, B)) # np.intersect1d()

[4 4 6 1 1 6 7 7 3 8] [ 5  5  9 10  8  5  3  8  5  6]
[3 6 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [83]:
# defaults = np.seterr(all = 'ignore')
# _ = np.seterr(**defaults)

NameError: name 'defaults' is not defined

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [81]:
np.sqrt(-1) == np.emath.sqrt(-1)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [79]:
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print(np.timedelta64(1, 'D'))

print(yesterday, today, tomorrow)

1 days
2019-04-06 2019-04-07 2019-04-08


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [70]:
# have no idea

D = np.arange("2016-07", "2016-08", dtype = 'datetime64[D]')
print(D)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [69]:
A = np.ones(1)
print(A)
B = np.ones(1)*2
print(B)

np.add(A, B, out = B)
np.divide(A, 2, out = A)
np.negative(A, out = A)
np.multiply(B, A, out = A)

[ 1.]
[ 2.]


array([-1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [58]:
A = np.random.uniform(1, 5, 10)
print(A)

print(A - A%1)
print(np.floor(A))
print(np.ceil(A) - 1)
print([np.int(i) for i in A])
print(A.astype(int))
print(np.trunc(A)) # search np.trunc


# help(np.around)

[ 4.06885149  1.11253639  4.80793153  1.31902064  4.15767944  3.912109
  4.59641328  2.45527512  4.11147207  1.34806586]
[ 4.  1.  4.  1.  4.  3.  4.  2.  4.  1.]
[ 4.  1.  4.  1.  4.  3.  4.  2.  4.  1.]
[ 4.  1.  4.  1.  4.  3.  4.  2.  4.  1.]
[4, 1, 4, 1, 4, 3, 4, 2, 4, 1]
[4 1 4 1 4 3 4 2 4 1]
[ 4.  1.  4.  1.  4.  3.  4.  2.  4.  1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [29]:
row = np.arange(0, 5)
# print(row)
M = row.reshape(1,5).repeat(5, axis = 0)
print(M)

[0 1 2 3 4]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [25]:
def gen_fun(tot = 10):
    for x in range(tot):
        yield x # what does yield mean??

Z = np.fromiter(gen_fun(), dtype = float, count = -1) # fromiter??
print(Z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [5]:
import numpy as np
# V = np.random.uniform(0, 1, 10)
V = np.linspace(0, 1, 11, endpoint = False)[1:]
print(V)



[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [83]:
A = np.random.random(10)
print(A)

A.sort()
print(A)

[0.98342794 0.31143792 0.28763828 0.97538469 0.88955774 0.46377578
 0.31556302 0.08668516 0.59926361 0.3653085 ]
[0.08668516 0.28763828 0.31143792 0.31556302 0.3653085  0.46377578
 0.59926361 0.88955774 0.97538469 0.98342794]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [81]:
A = np.random.random(1000)
%timeit np.sum(A)

%timeit np.add.reduce(A)

5.21 µs ± 292 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.36 µs ± 66.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [76]:
A  = np.random.random(10)
B = np.random.random(10)

print(np.allclose(A, B)) #check values only


A = np.arange(8).reshape(4,2)
B = np.arange(8).reshape(2,4)
C = np.arange(8).reshape(4,2)
print(np.array_equal(A, B)) # check both value and shape
print(np.array_equal(A, C))

False
False
True


#### 43. Make an array immutable (read-only) (★★☆)

In [67]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [65]:
A = np.random.random(10)
print(A)
max_ind = A.argmax()
A[max_ind] = 0

print(A)

[0.48798172 0.92058994 0.86514264 0.27770066 0.10229023 0.74506203
 0.88213111 0.98041083 0.47865767 0.76785365]
[0.48798172 0.92058994 0.86514264 0.27770066 0.10229023 0.74506203
 0.88213111 0.         0.47865767 0.76785365]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [64]:
A = np.zeros((5,5), [('x', float), ('y', float)])
# print(A)
A['x'], A['y'] = np.meshgrid(np.linspace(0, 1, 5),
                            np.linspace(0, 1, 5))
print(A)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [60]:
X = np.arange(8).reshape(8,1)
Y = (X + 0.5).reshape(1,8)
# print(X)
# print(Y)

C = 1.0 / (X - Y) #np.subtract.outter(X, Y)
print(C) # np.linalg.det(C), check this

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [46]:
for dtype in (np.int8, np.int32, np.int64):
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
    
print('\n')

for dtype in (np.float32, np.float64):
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [43]:
np.set_printoptions(threshold = np.nan) #check np.set_printoptions()
A = np.zeros((10,10))
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [39]:
V = np.random.random(20)
print(V)
s = 12
cs = np.abs(s - V).argmin()
print(V[cs])

[0.13400427 0.33452375 0.39245032 0.04578356 0.68746905 0.73070393
 0.68812631 0.36167445 0.80270533 0.61079573 0.93569894 0.60267435
 0.92213783 0.594124   0.61465344 0.98660659 0.48811599 0.59590922
 0.71204005 0.66134963]
0.9866065934568508


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [34]:
V = np.random.random(size = (100, 2))
# print(V)
X, Y = np.atleast_2d(V[:, 0], V[:, 1])
dist = np.sqrt((X - X.T)**2 + (Y-Y.T)**2)
print(dist)

import scipy.spatial
D = scipy.spatial.distance.cdist(V, V)
print(D)

[[0.         0.57626794 0.42354765 ... 0.40086812 0.13359482 0.71951036]
 [0.57626794 0.         0.19885954 ... 0.3667043  0.5756996  0.23310205]
 [0.42354765 0.19885954 0.         ... 0.17516746 0.46131858 0.2963675 ]
 ...
 [0.40086812 0.3667043  0.17516746 ... 0.         0.48547818 0.38252261]
 [0.13359482 0.5756996  0.46131858 ... 0.48547818 0.         0.75321356]
 [0.71951036 0.23310205 0.2963675  ... 0.38252261 0.75321356 0.        ]]
[[0.         0.57626794 0.42354765 ... 0.40086812 0.13359482 0.71951036]
 [0.57626794 0.         0.19885954 ... 0.3667043  0.5756996  0.23310205]
 [0.42354765 0.19885954 0.         ... 0.17516746 0.46131858 0.2963675 ]
 ...
 [0.40086812 0.3667043  0.17516746 ... 0.         0.48547818 0.38252261]
 [0.13359482 0.5756996  0.46131858 ... 0.48547818 0.         0.75321356]
 [0.71951036 0.23310205 0.2963675  ... 0.38252261 0.75321356 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [25]:
A_f32 = np.arange(10, dtype = np.float32)
print(A_f32)
A_f32 = A_f32.astype(np.int32, copy = False) #review np.datatype
print(A_f32)
print(A_f32 is A_f32)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]
True


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [13]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11""")
# print(s)
A = np.genfromtxt(s, delimiter = ',', dtype = np.int)
print(A)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [9]:
import numpy as np
A = np.arange(10).reshape(2,5)
print(A)
for index, value in np.ndenumerate(A):
    print(index, value)

print('\n')

for index in np.ndindex(A.shape):
    print(index, A[index])


[[0 1 2 3 4]
 [5 6 7 8 9]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(0, 4) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(1, 4) 9


(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(0, 4) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(1, 4) 9


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [34]:
X, Y = np.meshgrid(np.linspace(-1, 1, 5), np.linspace(-1, 1, 5)) # np.meshgrid??
D = np.sqrt(X**2 + Y**2)
mu, sigma = 0, 1
G = np.exp(-(D-mu)**2/(2*sigma**2))
print(G)

[[0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.60653066 0.8824969  1.         0.8824969  0.60653066]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [28]:
A = np.random.randint(1, 20, size = (4,5))
print(A)

np.put(A, np.random.choice(range(4*5), 3, replace=False),0) # np.put(); np.random.choice()
print(A)

[[ 3 13  3 11  8]
 [17  1  9  3 17]
 [ 3 10 12 14 12]
 [16 12  3 13  8]]
[[ 3 13  3  0  8]
 [17  1  9  0 17]
 [ 3  0 12 14 12]
 [16 12  3 13  8]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [26]:
A = np.random.normal(size = (2,3))
print(A)
# print(A.mean(axis = 1))

print(A - A.mean(axis = 1).reshape(2,1))
print(A - A.mean(axis = 1, keepdims=True)) # newer version

[[-0.11157846  1.13337173 -0.28388762]
 [ 0.4399681  -0.6842315   0.87861428]]
[[-0.35754701  0.88740318 -0.52985617]
 [ 0.22851781 -0.89568179  0.66716398]]
[[-0.35754701  0.88740318 -0.52985617]
 [ 0.22851781 -0.89568179  0.66716398]]


#### 59. How to sort an array by the nth column? (★★☆)

In [21]:
A = np.random.randint(0, 10, (3,4))
print(A)
print(A[A[:,1].argsort()]) #.argsort()

[[7 0 8 7]
 [6 4 5 6]
 [1 7 8 8]]
[[7 0 8 7]
 [6 4 5 6]
 [1 7 8 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [18]:
A = np.random.normal(size = (4,5))
print(A)

print(~A.any(axis = 0).any()) # ~ for negateve; .any() to check null 

[[ 0.13370222  0.21024611 -0.97859846 -0.55794707 -0.73162995]
 [ 2.02753922  0.18463726  0.27780938  0.4755542   0.82288876]
 [ 0.12191454  0.19964455 -0.96246003 -0.6803074  -1.29822595]
 [-1.08895148  0.04739167 -0.33227727 -0.79788512 -1.81007905]]
[False False False False False]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [10]:
def NearestValue(v, arr):
    ind = np.abs(v - arr).argmin()
    return(arr.flat[ind]) #.flat? - flat ndarry to 1D array

A = np.random.uniform(0, 1, 10)
print(A)

NearestValue(0.3, A)

[0.53625206 0.11231147 0.99505758 0.31659379 0.85003377 0.05337942
 0.2944764  0.58317666 0.66826709 0.61172706]


0.294476397745027

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [7]:
A1 = np.arange(3).reshape(1,3)
A2 = np.arange(3).reshape(3,1)

it = np.nditer([A1,A2,None]) # search for nditer
for x,y,z in it: z[...] = x + y
print(it.operands[2]) 


[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [4]:
import numpy as np
class NameArray(np.ndarray):
    def __new__(cls, array, name = 'no name'):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', 'no name')
        
TestArray = NameArray(np.arange(9), 'toy array')
print(TestArray.name)
print(TestArray.info)

toy array
no name


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)

print(I)
print(np.bincount(I))

Z += np.bincount(I)
print(Z)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
## study axis index of an array

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

#### 72. How to swap two rows of an array? (★★★)

In [ ]:
A = np.arange(25).reshape(5,5)
print(A)
print(A[(0,1),])
# A[(0,1), ] = A[(1,0), ]
A[[0,1]] = A[[1,0]]
print(A)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
# what is np.bincount?
import numpy as np
C = np.bincount([1,1,2,3,4,4,6])
print(C)
A = np.repeat(np.arange(len(C)), C)
print(A)

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
import numpy as np
np.random.seed(94065)
A = np.arange(0, 10, dtype = np.uint32)

def moving_average(arr, window_size):
    print(arr)
    arr_split = np.lib.stride_tricks.as_strided(arr, (arr.size - window_size + 1, window_size), (arr.itemsize, arr.itemsize))
    print(arr_split)
    means = np.mean(arr_split, axis = 1)
    return(means)

moving_average(A, 4)
    


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [ ]:
Z = np.arange(0, 10, dtype = np.uint32)
print(Z)
# print(Z.itemsize) # what is Z.itemsize and Z.strides??
n = 3
ZZ = np.lib.stride_tricks.as_strided(Z, (8,3), (Z.itemsize,Z.itemsize))
print(ZZ)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z) # out option

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
np.random.seed(94065)
P0 = np.random.uniform(-1, 1, (10, 2))
P1 = np.random.uniform(-1, 1, (10, 2))

print(P0 - P1)
print((P0 - P1)**2)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [ ]:
Z = np.arange(1, 15, dtype = np.uint32)
n = 4
# R = [Z[i:i+4] for i in range(len(Z)-4+1)] # what is the difference b/t list and np array??
R = np.lib.stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

#### 82. Compute a matrix rank (★★★)

In [ ]:
## matrix decomposition

#### 83. How to find the most frequent value in an array?

In [ ]:
Z = np.random.randint(0,10,100)
# print(Z)
print(np.bincount(Z))#np.bincount()??
print(np.bincount(Z).argmax())

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
B = np.random.normal(0, 1, (10,10))
# print(B.strides + B.strides) # what is strides for an array??
n = 3
i = B.shape[0] - n + 1
j = B.shape[1] - n + 1
C = np.lib.stride_tricks.as_strided(B, shape = (i, j, n, n), strides = B.strides + B.strides)
print(C.shape)


#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [ ]:
# create an symmetric matrix
n = 10
N = np.int((n+1)*n/2)
A = range(N)
B = np.zeros((n, n))
k = 0
for i in range(N):
    for j in range(i, n):
        B[i,j] = B[j,i] = A[k]
        k = k + 1
    
print(B)
    



#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
Z = np.ones((16,16))
k = 4

print(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0))

S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]]) # what is argpartition??

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
# definition of record array?

Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
print(Z)
print(Z.T)
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
x = np.random.rand(np.int(1e5))
print(x.size)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
A = np.random.randint(0, 5, (8,3))
B = np.random.randint(0, 3, (2,2))
print(A)
print(B)
C = (A[..., np.newaxis, np.newaxis] == B) #broadcasting to dimension of B
print(C)
print(C.any((3,1))) # not understand, what does this mean??
print(np.where(C.any((3,1)).all(1))[0])


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
X = np.random.randint(0, 3, (10, 3))
print(X)
# print(X[:,1:])
# print(X[:,:-1])
idx = np.all(X[:, 1:] == X[:,:-1], axis = -1)
X[~idx]

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
np.random.seed(94065)
Z = np.random.randint(0,2,(6,3))
T = np.unique(Z, axis = -1)
print(T)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [36]:
X = np.random.randint(0, 5, (10, 10))
# print(X)
def multinomial_row(X, n = 25):
    M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1) # how does this work
    sums = X.sum(axis = -1)
#     print(sums)
    M &= (sums == n) # M &= b <--> M = M & b
    return(X[M])

X_sel = multinomial_row(X)
print(X_sel)
    

[[0 3 1 0 4 2 4 3 3 4]
 [4 2 2 3 0 0 3 1 1 3]
 [0 0 0 3 0 3 4 4 3 3]
 [4 2 3 3 1 2 2 0 3 3]
 [1 4 0 0 0 1 4 4 2 0]
 [1 2 0 3 3 2 2 0 0 3]
 [1 3 1 2 2 3 0 4 4 1]
 [1 0 4 2 1 0 1 0 3 3]
 [0 2 1 0 3 4 2 2 0 3]
 [4 0 0 4 1 1 3 0 0 2]]
[16 18 12 20 15 18 25 18 19 25]
[[1 3 1 2 2 3 0 4 4 1]
 [4 0 0 4 1 1 3 0 0 2]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [17]:
import numpy as np
np.random.seed(94080)
X = np.random.normal(0, 1, 10000)
# print(X.mean(axis=0))
bt_idx = np.random.randint(0, X.size, (1000, X.size))
X_bt_means = X[bt_idx].mean(axis = 1)
# print(X_bt_means.size)
print(np.percentile(X_bt_means, (2.5, 97.5)))

-0.013763593476203923
1000
[-0.03357029  0.00698166]
